### ISSUE TITLE
create issue breakdown: Ascent/Entry

### ISSUE THREAD

**Issue by mdbernard** [intern-space-program/ksp#15]
See RPOD for reference in #16 

Define these points in a comment in this issue:
- [x] Define Take-Over points (where does the team take control of the vehicle?)
- [x] Define Hand-Over points (where does the team stop controlling the vehicle?)
- [x] Define Event Sequences (describe, in a sentence, what the team does with the vehicle)

Create an issue...
- [x] for each Event Sequence to create fine-grained procedures in the form of a markdown file 
- [x] to determine algorithm similarity between Event Sequences (i.e. where could code be reused?) (#35)
- [x] to program each general algorithm/function to be used across multiple Event Sequences (#36)
- [x] to program a controlling function for each Event Sequence (#28)
- [x] to program a Continuous Integration test for each Event Sequence's controlling function (#37)
- [x] to program unit tests for each function used throughout all of the team's Event Sequence scripts (except the controlling functions) (#38)

**Comment by mdbernard** [comment]
The mission's commanding script will begin with pre-launch preparation and then hand off control to A/E while SLS is on the launchpad, no stages activated.

TO1: SLS is on the launchpad.
ES1: SLS flies to Kerbin orbit.
HO1

Other teams handle trans-lunar injection, lunar landing, lunar ascent, trans-Kerbin injection.

TO2: Orion SM is still attached, 100 km above Kerbin's surface, returning from Mun.
ES2: Separate from SM and fly through atmosphere. Splashdown.
HO2
