### ISSUE TITLE
create issue breakdown: RPOD

### ISSUE THREAD

**Issue by mdbernard** [intern-space-program/ksp#16]
Define these points in a comment in this issue:
- [x] Define Take-Over points (where does the team take control of the vehicle?)
- [x] Define Hand-Over points (where does the team stop controlling the vehicle?)
- [x] Define Event Sequences (describe, in a sentence, what the team does with the vehicle)

Create an issue...
- [x] for each Event Sequence to create fine-grained procedures in the form of a markdown file (#21, #22, #23, #24, #25)
- [x] to determine algorithm similarity between Event Sequences (i.e. where could code be reused?) (#33)
- [x] to program each general algorithm/function to be used across multiple Event Sequences (#34)
- [x] to program a controlling function for each Event Sequence (#27)
- [x] for each Event Sequence to program a Continuous Integration test for its controlling function (#32)
- [x] to program unit tests for each function used across all of the team's Event Sequence Scripts (#31)

**Comment by mdbernard** [comment]
TO: Take Over Point
ES: Event Sequence
HO: Hand Over Point

Orbit team will set up Mun capture burn such that Orion is near Gateway and near the Gateway apoapsis.

TO1: Rendezvous point with Gateway at apoapsis
ES1: Orion approach Gateway and dock
ES2: HLS undock from Gateway and moves to safe distance
HO1

HLS lands. Ascent stage sent on suborbital trajectory intercepting tug stage.

TO2: Intercept with tug.
ES3: Circularize and match tug's orbit. Approach and dock to tug.
HO2

HLS sent on intercept trajectory with Gateway.

TO3: Intercept with Gateway.
ES4: Approach and dock HLS to Gateway.
ES5: Orion undocks from Gateway and moves to a safe distance.
HO3
